// File generated by FlutterFire CLI.
// This is a mock configuration for development
// Replace with your actual Firebase configuration from Firebase Console

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY59aNn2BErQo97i8SY3jZDNkO1brQDrM',
    appId: '1:200804731302:android:04ca904e762bab823ea767',
    messagingSenderId: '200804731302',
    projectId: 'taskflow-efae5',
    authDomain: 'taskflow-efae5.firebaseapp.com',
    storageBucket: 'taskflow-efae5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY59aNn2BErQo97i8SY3jZDNkO1brQDrM',
    appId: '1:200804731302:android:04ca904e762bab823ea767',
    messagingSenderId: '200804731302',
    projectId: 'taskflow-efae5',
    storageBucket: 'taskflow-efae5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY59aNn2BErQo97i8SY3jZDNkO1brQDrM',
    appId: '1:200804731302:android:04ca904e762bab823ea767',
    messagingSenderId: '200804731302',
    projectId: 'taskflow-efae5',
    storageBucket: 'taskflow-efae5.firebasestorage.app',
    iosBundleId: 'com.example.smartBuy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY59aNn2BErQo97i8SY3jZDNkO1brQDrM',
    appId: '1:200804731302:android:04ca904e762bab823ea767',
    messagingSenderId: '200804731302',
    projectId: 'taskflow-efae5',
    storageBucket: 'taskflow-efae5.firebasestorage.app',
    iosBundleId: 'com.example.smartBuy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDY59aNn2BErQo97i8SY3jZDNkO1brQDrM',
    appId: '1:200804731302:android:04ca904e762bab823ea767',
    messagingSenderId: '200804731302',
    projectId: 'taskflow-efae5',
    authDomain: 'taskflow-efae5.firebaseapp.com',
    storageBucket: 'taskflow-efae5.firebasestorage.app',
  );
}
