// File generated by FlutterFire CLI.
// This is a mock configuration for development
// Replace with your actual Firebase configuration from Firebase Console

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDummy-Web-Key-Replace-With-Real',
    appId: '1:1234567890:web:abcdef1234567890abcdef',
    messagingSenderId: '1234567890',
    projectId: 'taskflow-demo',
    authDomain: 'taskflow-demo.firebaseapp.com',
    storageBucket: 'taskflow-demo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDummy-Android-Key-Replace-With-Real',
    appId: '1:1234567890:android:abcdef1234567890abcdef',
    messagingSenderId: '1234567890',
    projectId: 'taskflow-demo',
    storageBucket: 'taskflow-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDummy-iOS-Key-Replace-With-Real',
    appId: '1:1234567890:ios:abcdef1234567890abcdef',
    messagingSenderId: '1234567890',
    projectId: 'taskflow-demo',
    storageBucket: 'taskflow-demo.appspot.com',
    iosBundleId: 'com.example.smartBuy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDummy-macOS-Key-Replace-With-Real',
    appId: '1:1234567890:ios:abcdef1234567890abcdef',
    messagingSenderId: '1234567890',
    projectId: 'taskflow-demo',
    storageBucket: 'taskflow-demo.appspot.com',
    iosBundleId: 'com.example.smartBuy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDummy-Windows-Key-Replace-With-Real',
    appId: '1:1234567890:web:abcdef1234567890abcdef',
    messagingSenderId: '1234567890',
    projectId: 'taskflow-demo',
    authDomain: 'taskflow-demo.firebaseapp.com',
    storageBucket: 'taskflow-demo.appspot.com',
  );
}
